-- Tablas de resultados de los procesos batch (compatibles con PostgreSQL y H2).
-- Las tablas de control de Spring Batch (BATCH_*) las crea Spring Boot automáticamente.

CREATE TABLE IF NOT EXISTS registro_rechazado (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id BIGINT       NOT NULL,
    job          VARCHAR(60)  NOT NULL,
    archivo      VARCHAR(200) NOT NULL,
    linea        INTEGER,
    contenido    VARCHAR(500),
    motivo       VARCHAR(300) NOT NULL,
    fecha        TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rechazo_instancia ON registro_rechazado (instancia_id);

-- Job 1: Reporte de Transacciones Diarias
CREATE TABLE IF NOT EXISTS transaccion_diaria (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id            BIGINT         NOT NULL,
    archivo                 VARCHAR(200)   NOT NULL,
    linea                   INTEGER        NOT NULL,
    registro_id             BIGINT         NOT NULL,
    fecha                   DATE           NOT NULL,
    monto                   NUMERIC(19, 2) NOT NULL,
    tipo                    VARCHAR(30)    NOT NULL,
    fecha_original          VARCHAR(20)    NOT NULL,
    formato_fecha_corregido BOOLEAN        NOT NULL,
    es_anomalia             BOOLEAN        NOT NULL,
    motivo_anomalia         VARCHAR(200),
    procesado_en            TIMESTAMP      NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_transaccion_instancia ON transaccion_diaria (instancia_id, fecha);

CREATE TABLE IF NOT EXISTS resumen_transacciones_diario (
    instancia_id      BIGINT         NOT NULL,
    fecha             DATE           NOT NULL,
    total_registros   INTEGER        NOT NULL,
    cantidad_creditos INTEGER        NOT NULL,
    cantidad_debitos  INTEGER        NOT NULL,
    monto_creditos    NUMERIC(19, 2) NOT NULL,
    monto_debitos     NUMERIC(19, 2) NOT NULL,
    saldo_neto        NUMERIC(19, 2) NOT NULL,
    anomalias         INTEGER        NOT NULL,
    PRIMARY KEY (instancia_id, fecha)
);

-- Job 2: Cálculo de Intereses Mensuales
CREATE TABLE IF NOT EXISTS interes_mensual (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id     BIGINT         NOT NULL,
    archivo          VARCHAR(200)   NOT NULL,
    linea            INTEGER        NOT NULL,
    periodo          VARCHAR(7)     NOT NULL,
    cuenta_id        BIGINT         NOT NULL,
    nombre           VARCHAR(100)   NOT NULL,
    tipo             VARCHAR(20)    NOT NULL,
    edad             INTEGER        NOT NULL,
    saldo            NUMERIC(19, 2) NOT NULL,
    tasa_mensual     NUMERIC(12, 8) NOT NULL,
    interes          NUMERIC(19, 2) NOT NULL,
    saldo_proyectado NUMERIC(19, 2) NOT NULL,
    hash_registro    VARCHAR(64)    NOT NULL,
    procesado_en     TIMESTAMP      NOT NULL,
    CONSTRAINT uk_interes_registro UNIQUE (instancia_id, archivo, hash_registro)
);

-- Job 3: Estados de Cuenta Anuales
CREATE TABLE IF NOT EXISTS movimiento_anual (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id   BIGINT         NOT NULL,
    archivo        VARCHAR(200)   NOT NULL,
    linea          INTEGER        NOT NULL,
    cuenta_id      BIGINT         NOT NULL,
    fecha          DATE           NOT NULL,
    anio           INTEGER        NOT NULL,
    transaccion    VARCHAR(20)    NOT NULL,
    monto          NUMERIC(19, 2) NOT NULL,
    monto_original VARCHAR(30)    NOT NULL,
    descripcion    VARCHAR(200)   NOT NULL,
    ajustado       BOOLEAN        NOT NULL,
    procesado_en   TIMESTAMP      NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_movimiento_anual ON movimiento_anual (instancia_id, anio, cuenta_id);

CREATE TABLE IF NOT EXISTS estado_cuenta_anual (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id          BIGINT         NOT NULL,
    anio                  INTEGER        NOT NULL,
    cuenta_id             BIGINT         NOT NULL,
    total_depositos       NUMERIC(19, 2) NOT NULL,
    total_retiros         NUMERIC(19, 2) NOT NULL,
    total_compras         NUMERIC(19, 2) NOT NULL,
    total_pagos           NUMERIC(19, 2) NOT NULL,
    total_cargos          NUMERIC(19, 2) NOT NULL,
    saldo_neto            NUMERIC(19, 2) NOT NULL,
    cantidad_movimientos  INTEGER        NOT NULL,
    movimientos_ajustados INTEGER        NOT NULL,
    generado_en           TIMESTAMP      NOT NULL
);
