-- Esquema del microservicio de Gestión de Cuentas (compatible con PostgreSQL y H2)
CREATE TABLE cuentas (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                 VARCHAR(30)    NOT NULL UNIQUE,
    cliente_id             BIGINT         NOT NULL,
    tipo                   VARCHAR(20)    NOT NULL,
    saldo                  NUMERIC(19, 2) NOT NULL,
    estado                 VARCHAR(20)    NOT NULL,
    pin_hash               VARCHAR(100),
    intentos_fallidos_pin  INTEGER        NOT NULL DEFAULT 0,
    fecha_apertura         TIMESTAMP      NOT NULL,
    fecha_cierre           TIMESTAMP,
    version                BIGINT         NOT NULL DEFAULT 0
);
CREATE INDEX idx_cuentas_cliente ON cuentas (cliente_id);

CREATE TABLE movimientos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id        BIGINT         NOT NULL REFERENCES cuentas (id),
    tipo             VARCHAR(10)    NOT NULL,
    monto            NUMERIC(19, 2) NOT NULL,
    saldo_resultante NUMERIC(19, 2) NOT NULL,
    referencia       VARCHAR(80)    NOT NULL UNIQUE,
    descripcion      VARCHAR(200),
    fecha            TIMESTAMP      NOT NULL
);
CREATE INDEX idx_movimientos_cuenta ON movimientos (cuenta_id, fecha);
