-- Esquema del microservicio de Gestión de Clientes (compatible con PostgreSQL y H2)
CREATE TABLE clientes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut              VARCHAR(12)  NOT NULL UNIQUE,
    nombres          VARCHAR(80)  NOT NULL,
    apellidos        VARCHAR(80)  NOT NULL,
    email            VARCHAR(120) NOT NULL,
    telefono         VARCHAR(20),
    direccion        VARCHAR(200),
    fecha_nacimiento DATE,
    segmento         VARCHAR(20)  NOT NULL,
    activo           BOOLEAN      NOT NULL,
    cuentas_activas  INTEGER      NOT NULL DEFAULT 0,
    fecha_registro   TIMESTAMP    NOT NULL,
    version          BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE notificaciones (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT       NOT NULL REFERENCES clientes (id),
    tipo       VARCHAR(30)  NOT NULL,
    nivel      VARCHAR(10)  NOT NULL,
    mensaje    VARCHAR(300) NOT NULL,
    evento_id  VARCHAR(120) NOT NULL,
    fecha      TIMESTAMP    NOT NULL,
    CONSTRAINT uk_notificacion_evento UNIQUE (evento_id, cliente_id)
);
CREATE INDEX idx_notificaciones_cliente ON notificaciones (cliente_id, fecha);
