spring:
  application:
    name: bff-web
  config:
    import: "configserver:${CONFIG_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 1.5
        max-attempts: 15
