-- Esquema del microservicio de Procesamiento de Pagos (compatible con PostgreSQL y H2)
CREATE TABLE pagos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referencia          VARCHAR(64)    NOT NULL UNIQUE,
    tipo                VARCHAR(20)    NOT NULL,
    estado              VARCHAR(20)    NOT NULL,
    cuenta_origen_id    BIGINT,
    cuenta_destino_id   BIGINT,
    cliente_origen_id   BIGINT,
    cliente_destino_id  BIGINT,
    monto               NUMERIC(19, 2) NOT NULL,
    descripcion         VARCHAR(200),
    canal               VARCHAR(10)    NOT NULL,
    motivo              VARCHAR(300),
    debito_aplicado     BOOLEAN        NOT NULL DEFAULT FALSE,
    credito_aplicado    BOOLEAN        NOT NULL DEFAULT FALSE,
    intentos            INTEGER        NOT NULL DEFAULT 0,
    fecha_creacion      TIMESTAMP      NOT NULL,
    fecha_actualizacion TIMESTAMP      NOT NULL,
    version             BIGINT         NOT NULL DEFAULT 0
);
CREATE INDEX idx_pagos_estado ON pagos (estado, fecha_actualizacion);
CREATE INDEX idx_pagos_origen ON pagos (cuenta_origen_id);
CREATE INDEX idx_pagos_destino ON pagos (cuenta_destino_id);
